In [1]:
()
favoritelang = ("Python", "Julia", "R")
x1 = (1, 2, 3)
x2 = (1, 2.0, "tmp")
x3 = (a=2, b=1+2)

(a = 2, b = 3)

In [2]:
length(x2)
x2[1], x2[2], x2[3]
c = x1[2] + x1[3]
x3.a, x3.b, x3[2]
in("tmp", x2), 0 in x2

(true, false)

In [3]:
phonebook = Dict("Иванов И.И." => ("867-5309","333-5544"),
                  "Бухгалтерия" => "555-2368")
keys(phonebook)
values(phonebook)
pairs(phonebook)
haskey(phonebook, "Иванов И.И.")        # true
phonebook["Сидоров П.С."] = "555-3344"
pop!(phonebook, "Иванов И.И.")          # ("867-5309","333-5544"), ключ удалён

a = Dict("foo" => 0.0, "bar" => 42.0)
b = Dict("baz" => 17, "bar" => 13.0)
merge(a, b), merge(b, a)

(Dict{String, Real}("bar" => 13.0, "baz" => 17, "foo" => 0.0), Dict{String, Real}("bar" => 42.0, "baz" => 17, "foo" => 0.0))

In [4]:
A = Set([1, 3, 4, 5])
B = Set("abrakadabra")            # уникальные буквы строки

S1 = Set([1,2]); S2 = Set([3,4])
issetequal(S1,S2)                 # false

S3 = Set([1,2,2,3,1,2,3,2,1]); S4 = Set([2,3,1])
issetequal(S3,S4)                 # true (оба {1,2,3})

C = union(S1,S2)                  # {1,2,3,4}
D = intersect(S1,S3)              # {1,2}
E = setdiff(S3,S1)                # {3}
issubset(S1,S4)                   # true
push!(S4, 99)                     # {1,2,3,99}
pop!(S4)                          # удаляет произвольный элемент (порядок не гарантирован)

2

In [5]:
empty_array_1 = []
empty_array_2 = (Int64)[]
empty_array_3 = (Float64)[]
a = [1, 2, 3]
b = [1 2 3]
A = [[1, 2, 3] [4, 5, 6] [7, 8, 9]]   # 3x3, каждый вектор — СТОЛБЕЦ
B = [[1 2 3]; [4 5 6]; [7 8 9]]       # 3x3, каждый вектор — СТРОКА
c = rand(1,8)
C = rand(2,3)
D = rand(4,3,2)                       # трёхмерный, значения случайны каждый раз

roots = [sqrt(i) for i in 1:10]
ar_1 = [3*i^2 for i in 1:2:9]                       # [3, 27, 75, 147, 243]
ar_2 = [i^2 for i=1:10 if (i^2%5!=0 && i^2%4!=0)]   # [1, 9, 49, 81]

length(A), ndims(A), size(A), size(A,1)
copy(A)
ones(5); ones(2,3); zeros(4)
fill(3.5,(3,2))
repeat([1,2],3,3)
repeat([1 2],3,3)

a = collect(1:12)
b = reshape(a,(2,6))
b'
transpose(b)

ar = rand(10:20, 10, 5)      
ar[:, 2]
ar[:, [2, 5]]
ar[:, 2:4]
ar[[2, 4, 6], [1, 5]]
ar[1, 3:end]
sort(ar,dims=1)
sort(ar,dims=2)
ar .> 14
findall(ar .> 14)

26-element Vector{CartesianIndex{2}}:
 CartesianIndex(4, 1)
 CartesianIndex(5, 1)
 CartesianIndex(8, 1)
 CartesianIndex(9, 1)
 CartesianIndex(10, 1)
 CartesianIndex(1, 2)
 CartesianIndex(2, 2)
 CartesianIndex(3, 2)
 CartesianIndex(4, 2)
 CartesianIndex(7, 2)
 CartesianIndex(10, 2)
 CartesianIndex(1, 3)
 CartesianIndex(2, 3)
 CartesianIndex(3, 3)
 CartesianIndex(4, 3)
 CartesianIndex(7, 3)
 CartesianIndex(8, 3)
 CartesianIndex(1, 4)
 CartesianIndex(2, 4)
 CartesianIndex(3, 4)
 CartesianIndex(6, 4)
 CartesianIndex(1, 5)
 CartesianIndex(4, 5)
 CartesianIndex(5, 5)
 CartesianIndex(8, 5)
 CartesianIndex(10, 5)

In [6]:
A = Set([0, 3, 4, 9])
B = Set([1, 3, 4, 7])
C = Set([0, 1, 2, 4, 7, 8, 9])
U = union(A, B, C)
Bc = setdiff(U, B)  # дополнение B

P = union(intersect(A,B), intersect(A,Bc), intersect(A,C), intersect(B,C))
println(P)


Set([0, 4, 7, 9, 3, 1])


In [7]:
S1 = Set([1, "два", 3.0, :четыре])   # смешанный тип Any
S2 = Set(["два", 5, 3.0])
union(S1, S2)
intersect(S1, S2)      # {"два", 3.0}
setdiff(S1, S2)

Set{Any} with 2 elements:
  :четыре
  1

In [9]:
N = 25
tmp = [4, 6, 3]

# 3.1-3.3
a31 = collect(1:N)
a32 = collect(N:-1:1)
a33 = vcat(1:N, N-1:-1:1)

# 3.4-3.8
a35 = fill(tmp[1], 10)
a36 = repeat(tmp, 10)
a37 = vcat(fill(tmp[1],11), fill(tmp[2],10), fill(tmp[3],10))
a38 = vcat(fill(tmp[1],10), fill(tmp[2],20), fill(tmp[3],30))

# 3.9
a39 = vcat(2^tmp[1], 2^tmp[2], fill(2^tmp[3], 4))   # [16, 64, 8, 8, 8, 8]
count_6 = sum(count(c -> c =='6', string(x)) for x in a39)
println(a39, "  цифра 6 встречается: ", count_6)     # ожидаемо: 2

# 3.10
using Statistics
x310 = 3:0.1:6
y310 = exp.(x310) .* cos.(x310)
mean(y310)

# 3.11
i311 = 3:3:36; j311 = 1:3:34
xs311 = 0.1 .* i311; ys311 = 0.2 .* j311
pairs311 = collect(zip(xs311, ys311))

# 3.12
v312 = [2.0^i / i for i in 1:25]

# 3.13
v313 = ["fn$i" for i in 1:30]

# 3.14
using Random
n = 250
x = rand(0:999, n)
y = rand(0:999, n)

d1 = y[2:end] .- x[1:end-1]
d2 = x[1:end-2] .+ 2 .* x[2:end-1] .- x[3:end]
d3 = sin.(y[1:end-1]) ./ cos.(x[2:end])
s  = sum(exp.(-x[2:end]) ./ (x[1:end-1] .+ 10))

big_y   = y[y .> 600]
idx_big = findall(y .> 600)
x_at_big_y = x[idx_big]

xbar = mean(x)
d4 = sqrt.(abs.(x .- xbar))

near_max = count(abs.(y .- maximum(y)) .<= 200)
n_even = count(iseven, x)
n_odd  = count(isodd, x)
n_div7 = count(v -> v % 7 == 0, x)

x_sorted_by_y = x[sortperm(y)]
top10 = sort(x, rev=true)[1:10]
x_unique = unique(x)

[16, 64, 8, 8, 8, 8]  цифра 6 встречается: 2


227-element Vector{Int64}:
 545
 732
 268
 597
 294
 404
 637
 320
 379
 877
 418
 348
 360
   ⋮
 376
 445
 911
 767
 686
 586
 742
 934
 143
 162
 272
 703

In [10]:
squares = [i^2 for i in 1:100]
squares[end] 

10000

In [11]:
import Pkg; Pkg.add("Primes")
using Primes

myprimes = primes(1000)
length(myprimes)
myprimes[89]
myprimes[89:99]

    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
    Updating `~/Project.toml`
  [27ebfcd6] + Primes v0.5.7
    Updating `~/Manifest.toml`
  [18e54dd8] + IntegerMathUtils v0.1.4
  [27ebfcd6] + Primes v0.5.7
Precompiling project...
  ✓ LaTeXStrings
  ✓ Tables
  ✓ Crayons
  ✓ SentinelArrays
  ✓ StringManipulation
  ✓ PrettyTables
  ✓ DataFrames
  7 dependencies successfully precompiled in 51 seconds. 45 already precompiled.


11-element Vector{Int64}:
 461
 463
 467
 479
 487
 491
 499
 503
 509
 521
 523

In [12]:
# 6.1
s1 = sum(i^3 + 4i^2 for i in 10:100)
println(s1)   # ожидаемо: 26852735

# 6.2
s2 = sum(2.0^i/i + 3.0^i/i^2 for i in 1:25)
println(s2)   # порядок величины ~1.35 млрд (доминирует последнее слагаемое)

# 6.3
terms = [2k/(2k+1) for k in 1:19]     # 2/3, 4/5, 6/7, ..., 38/39
partial = cumsum(terms)
s3 = 1 + sum(partial)
println(s3)

26852735
2.1291704368143802e9
170.16669918752706
